# Generated by Django 2.2.3 on 2019-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='publishdate',
            field=models.DateField(verbose_name='publish date'),
        ),
    ]
