# Generated by Django 2.2.3 on 2019-09-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_purchaser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchaser',
            new_name='Purchase',
        ),
    ]
