# Generated by Django 2.2.3 on 2019-09-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190922_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchasedate']},
        ),
        migrations.AddField(
            model_name='comic',
            name='shops',
            field=models.ManyToManyField(to='main_app.Shop'),
        ),
    ]
